require 'rubygems'
require 'fileutils'

load File.join(File.dirname(__FILE__), "buildwise.rake")

BUILDWISE_QUICK_PROJECT_ID = "agiletravel-quick-build-gauge" 
BUILDWISE_FULL_PROJECT_ID = "agiletravel-full-build-gauge"
BUILDWISE_URL = ENV["BUILDWISE_MASTER"] || "http://buildwise.macmini"

FULL_BUILD_MAX_TIME = 60 * 60   # 1 hour
FULL_BUILD_CHECK_INTERVAL = 30  # 1 minute

$test_dir =  File.expand_path(File.dirname(__FILE__))  # change to aboslution path if invoktion is not this directory

# Preqrueisite
# - Gauge + Ruby with xml-report plugin installed

desc "run all tests in this folder"
task "ui_tests:quick"  do
  
  ### the below run all test scripts under test folder, but without reporting  
  # 
  # `python -m unittest  discover test -p "*_test.py"`

  ## Runing individually
  #
  # tests_for_quick_build.each do |file|
  #   `python #{file}`
  # end
  
  ## Runing with nose
  # 
  reports_dir =  File.join(File.dirname(__FILE__), "reports")
  FileUtils.rm_rf(reports_dir) if File.exists?(reports_dir)
  FileUtils.mkdir_p(reports_dir)
  FileUtils.chdir(File.dirname(__FILE__))
  
  # system("nosetests --with-xunit --xunit-file=reports/TEST-SUITE.xml test")

  # The results under reports
  system("gauge specs")
end


def tests_for_quick_build
  # list test files to be run in a quick build
  [
    "#{$test_dir}/test/login.spec", 
    "#{$test_dir}/test/flight.spec",
  ]
end

def excluded_test_files
  ["test/ignored.spec"]
end


## Full Build
#
#  TODO - how to determin useing RSpec or Cucumber
#
desc "Running tests distributedly"
task "ci:ui_tests:full" do
  build_id = buildwise_start_build(:project_name => BUILDWISE_FULL_PROJECT_ID,
                                   :working_dir => File.expand_path(File.dirname(__FILE__)),
                                   :ui_test_dir => ["specs"],
                                   :excluded => excluded_test_files || [],
                                   :distributed => true,
                                   :test_framework => "unittest"
  )

  the_build_status = buildwise_build_ui_test_status(build_id)
  start_time = Time.now

  puts "[Rake] Keep checking build |#{build_id} | #{the_build_status}"
  while ((Time.now - start_time ) < FULL_BUILD_MAX_TIME) # test exeuction timeout
    the_build_status = buildwise_build_ui_test_status(build_id)
    puts "[Rake] #{Time.now} Checking build status: |#{the_build_status}|"
    if the_build_status == "OK"
      exit 0
    elsif the_build_status == "Failed"
      exit -1
    else 
      sleep FULL_BUILD_CHECK_INTERVAL  # check the build status every minute
    end
  end
  puts "[Rake] Execution UI tests expired"
  exit -2
end
