require 'rubygems'

BUILDWISE_QUICK_PROJECT_ID = "sitewise-quick-build" 
BUILDWISE_FULL_PROJECT_ID = "sitewise-full-build"
BUILDWISE_URL = ENV["BUILDWISE_MASTER"] || "http://buildwise.macmini"

FULL_BUILD_MAX_TIME = 60 * 60   # 1 hour
FULL_BUILD_CHECK_INTERVAL = 30  # 1 minute

madcow_sh = File.expand_path File.join(File.dirname(__FILE__), "runMadcow.sh")

desc "run all tests in this folder"
task "ui_tests:quick"  do
  `#{madcow_sh}`
end
